language: node_js
cache: yarn
node_js:
  - node
  - "10"
matrix:
  include:
    os: windows
    cache: false
    node_js: node
    env:
      - YARN_GPG=no
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/api
  on:
    branch: ose
    node_js: node
    os: linux
