environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - YARN_IGNORE_ENGINES=true yarn install

test_script:
  - yarn test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off
