name: Deno

on:
  push:
    tags:
      - "8.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x

      - name: Checkout postcss-deno
        uses: actions/checkout@v2
        with:
          repository: postcss/postcss-deno
          token: ${{ secrets.PAT }}

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: main
          path: postcss

      - name: Convert the code
        run: |
          rm -rf deno
          deno run --unstable --allow-write --allow-read to_deno.js
          deno fmt deno
          deno test --unstable --allow-read --allow-env deno/test/*

      - name: Get the tag name
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Commit the changes and create the tag
        run: |
          git config user.name deno-conversion
          git config user.email github-actions@github.com
          git add deno
          git commit -m "update code"
          git push
          git tag ${{ steps.get_version.outputs.VERSION }}
          git push --tags
